export const SET_BG_CLASSNAME = 'SET_BG_CLASSNAME';

export const FETCH_DATA_TRIGGERED = 'FETCH_DATA_TRIGGERED';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
